
name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          activate-environment: nanopore
          environment-file: environment.yml
          auto-activate-base: false

      - name: Verify environment
        shell: bash -l {0}
        run: |
          conda info --envs
          which python
          python - << 'EOF'
          import pandas, scipy, seaborn, sklearn
          import pysam, HTSeq, pod5
          print("All imports OK")
          EOF

      - name: Verify bio tools
        shell: bash -l {0}
        run: |
          samtools --version
          bedtools --version
